hudlUrl = "https://master.thorhudl.com"
uploadTeamId = "489196"
source_file_bucket = "hudl-encoding-test-bed"
source_file_key = "single_mp4/5ea08edf8cd3bb090877b0e1.mp4"
loginURL = "https://master.admin.thorhudl.com/login"
